Basic autoconf make install should work
git-svn-id: https://parflow.svn.cloudforge.com/parflow/parflow@92 39af3fb0-ca4e-0410-adf9-b4ae76d04516

diff --git a/branches/smith84/parflow/configure b/branches/smith84/parflow/configure
--- a/branches/smith84/parflow/configure
+++ b/branches/smith84/parflow/configure
@@ -1762,7 +1762,7 @@ ac_config_headers="$ac_config_headers include/parflow_config.h:config/parflow_co
 
 
 ac_aux_dir=
-for ac_dir in acmacros "$srcdir"/acmacros; do
+for ac_dir in ../acmacros "$srcdir"/../acmacros; do
   if test -f "$ac_dir/install-sh"; then
     ac_aux_dir=$ac_dir
     ac_install_sh="$ac_aux_dir/install-sh -c"
@@ -1778,8 +1778,8 @@ for ac_dir in acmacros "$srcdir"/acmacros; do
   fi
 done
 if test -z "$ac_aux_dir"; then
-  { { echo "$as_me:$LINENO: error: cannot find install-sh or install.sh in acmacros \"$srcdir\"/acmacros" >&5
-echo "$as_me: error: cannot find install-sh or install.sh in acmacros \"$srcdir\"/acmacros" >&2;}
+  { { echo "$as_me:$LINENO: error: cannot find install-sh or install.sh in ../acmacros \"$srcdir\"/../acmacros" >&5
+echo "$as_me: error: cannot find install-sh or install.sh in ../acmacros \"$srcdir\"/../acmacros" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
