Added autoconf support for AMPS
git-svn-id: https://parflow.svn.cloudforge.com/parflow/parflow/branches/smith84@103 39af3fb0-ca4e-0410-adf9-b4ae76d04516

diff --git a/parflow/configure b/parflow/configure
--- a/parflow/configure
+++ b/parflow/configure
@@ -692,6 +692,7 @@ MPIINCLUDE
 MPILIBDIRS
 MPILIBS
 MPIFLAGS
+AMPS
 SUNDIALS_C_FILES
 INSTDIR
 M4
@@ -1319,6 +1320,7 @@ Optional Packages:
   --with-MPICC=ARG        ARG is mpicc or similar MPI C compiling tool
   --with-mpi-libs=LIBS    LIBS is space-separated list of library names
                           needed for MPI, e.g. \"nsl socket mpi\"
+ --with-amps=AMPS_TYPE  Set the version of AMPS to use: seq, mpi1, smpi, win32
  --with-silo=PATH  Use SILO and optionally specify where SILO is installed.
   --with-sundials=PATH	Use the Sundials solver package
 			and specify where it is.
@@ -10894,6 +10896,55 @@ _ACEOF
 fi
 
 
+
+# Begin CASC_SUPPORT_AMPS
+# Determine which AMPS layer to support.
+# Defines AMPS
+
+# Check whether --with-amps was given.
+if test "${with_amps+set}" = set; then
+  withval=$with_amps;
+else
+  with_amps=seq
+fi
+
+
+case "$with_amps" in
+  no)
+    AMPS=seq
+  ;;
+  seq)
+    AMPS=seq
+  ;;
+  mpi1)
+    AMPS=mpi1
+  ;;
+  smpi)
+    AMPS=smpi
+  ;;
+  win32)
+    AMPS=win32
+  ;;
+  *)
+    { { echo "$as_me:$LINENO: error: Invalid AMPS version specified, use seq, mpi1, smpi, win32" >&5
+echo "$as_me: error: Invalid AMPS version specified, use seq, mpi1, smpi, win32" >&2;}
+   { (exit 1); exit 1; }; }
+  ;;
+esac
+{ echo "$as_me:$LINENO: result: configuring AMPS $AMPS support" >&5
+echo "${ECHO_T}configuring AMPS $AMPS support" >&6; }
+
+
+cat >>confdefs.h <<_ACEOF
+#define AMPS $AMPS
+_ACEOF
+
+
+# END CASC_SUPPORT_AMPS
+
+
+
+
   { echo "$as_me:$LINENO: checking for gettimeofday" >&5
 echo $ECHO_N "checking for gettimeofday... $ECHO_C" >&6; }
   if test "${casc_cv_gettimeofday+set}" = set; then
@@ -12131,6 +12182,7 @@ MPIINCLUDE!$MPIINCLUDE$ac_delim
 MPILIBDIRS!$MPILIBDIRS$ac_delim
 MPILIBS!$MPILIBS$ac_delim
 MPIFLAGS!$MPIFLAGS$ac_delim
+AMPS!$AMPS$ac_delim
 SUNDIALS_C_FILES!$SUNDIALS_C_FILES$ac_delim
 INSTDIR!$INSTDIR$ac_delim
 M4!$M4$ac_delim
@@ -12147,7 +12199,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 93; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 94; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
